Language bar and selector - Frontend
yalla-coop/universal-credit-support pull request #209
Opened 2022-11-15 14:29 UTC by cemalokten

#### Issues this PR relates to : 

- https://github.com/yalla-coop/cost-of-living-support/issues/53
- https://github.com/yalla-coop/cost-of-living-support/issues/53

=======

2022-11-16 07:53 UTC, fadeomar requested changes
- [ ] the code is not running, please make sure that everything is working as expected 
![image](https://user-images.githubusercontent.com/39485495/202119970-33980217-4bb5-47f9-95e3-b78b4de3dfae.png)

2022-11-16 07:53 UTC, fadeomar commented on client/src/components/Language/LanguageSelector/index.js
> +  lm: 'Italian',
duplicate key am

2022-11-18 17:02 UTC, cemalokten commented
@fadeomar Fixed this, when the COL version has been re-reviewed ill create a new patch to add the changes to this PR.

2022-11-22 14:10 UTC, fadeomar requested changes
- [x] each child in the language selector component needs a key
![image](https://user-images.githubusercontent.com/39485495/203332431-58abf65b-736a-4333-9b5f-f9fe5c1f0d3f.png)
  - [x] please make sure to use camel case for the properties names in SVG's, there are many errors in the console because of that 
![image](https://user-images.githubusercontent.com/39485495/203333185-034a127a-7be0-4b0b-be77-5b76b7fe4089.png)
  - [ ] when click at any flag n he language selector component it throw error : type error handleHide is not a function 
![image](https://user-images.githubusercontent.com/39485495/203335128-bbac9fed-3d89-412f-bc66-03a3ad3294a9.png)

2022-11-22 14:10 UTC, fadeomar commented on client/src/components/Icon/icons/German.js
> +        color-interpolation-filters="sRGB"
```suggestion
        colorInterpolationFilters="sRGB"
```

2022-11-22 14:10 UTC, fadeomar commented on client/src/components/Icon/icons/German.js
> +        color-interpolation-filters="sRGB"
use camelCase

2022-11-22 14:10 UTC, fadeomar commented on client/src/components/Icon/icons/Urdu.js
> +        stroke-width="0.5"
use camelCase

2022-11-22 14:10 UTC, fadeomar commented on client/src/components/Icon/icons/Urdu.js
> +        clip-rule="evenodd"
use camelCase

2022-11-22 14:10 UTC, fadeomar commented on client/src/components/Icon/icons/Urdu.js
> +        clip-rule="evenodd"
use camelCase

2022-11-22 14:10 UTC, fadeomar commented on client/src/components/Icon/index.js.rej
> +diff a/client/src/components/Icon/index.js b/client/src/components/Icon/index.js	(rejected hunks)
this file does not suppose to be pushed on the PR

2022-11-23 12:58 UTC, merged