Col #38 Edit contact details
yalla-coop/universal-credit-support pull request #215
Opened 2022-11-22 18:12 UTC by remaininlight

#### Issues this PR relates to
https://github.com/yalla-coop/cost-of-living-support/issues/38
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-22 18:13 UTC, remaininlight commented
Added google-libphonenumber because the client wouldn't compile without it 🤷‍♂️

2022-11-23 08:43 UTC, fadeomar requested changes
hey @remaininlight nice work but I've some notes: 
  - [ ] the page title should be change to (Edit account details)
  - [ ] the tip card that says (Please note that changing your unique link will mean we need to review your profile again ) need to be added before the button https://www.figma.com/file/EqDZxsZf5o6cFfDbqyBsnt/Wireframes?node-id=4617%3A19083&t=da3LfZoEdwgaf199-0 
  - [ ] the space between the page title and the (Below you can edit details for your customers such as your adviser contact line) line should be 32px 
![image](https://user-images.githubusercontent.com/39485495/203269750-8d413e92-0f84-40a9-bac7-8d37e3a53869.png)
  - [x] please tick the points that you have done in your PR in the original issue https://github.com/yalla-coop/cost-of-living-support/issues/38

2022-11-23 08:43 UTC, fadeomar commented on client/package.json
> +    "google-libphonenumber": "^3.2.31",
this should be in the dependencies not on devDependencies because we need it in the production

2022-11-23 16:47 UTC, remaininlight commented
> * the tip card that says (Please note that changing your unique link will mean we need to review your profile again )

Thanks for the feedback @fadeomar. This tip card has been outwitting me for a while, I've tried *exactly* the same code for this file as on CoL but there are still differences in the way the tip card displays:

Cost of Living:
![image](https://user-images.githubusercontent.com/4106946/203601531-f5ae5314-4308-4a1b-8337-48de60773ec7.png)

Universal Credit:
![image](https://user-images.githubusercontent.com/4106946/203602535-10877d7b-e26a-49fb-b7d0-bfef6b1ba21f.png)

Do you know why this might be please?

2022-11-24 11:41 UTC, merged