handle org delete account
yalla-coop/universal-credit-support pull request #220
Opened 2022-11-29 19:58 UTC by fadeomar

#### Issues this PR relates to
related PR : https://github.com/yalla-coop/cost-of-living-support/pull/106/
related issue : https://github.com/yalla-coop/cost-of-living-support/issues/37
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2022-11-30 05:15 UTC, RamyAlshurafa requested changes
- [ ] add migration files
- [x] get the changes from this commit https://github.com/yalla-coop/cost-of-living-support/pull/106/commits/8279a28c85b51494663fbcd1a5d5979ebd3a4ad7
- [x] I deleted my account but the organization was not deleted https://www.loom.com/share/a1013e37b2ca4bb8a9ff1528006dbdec

2022-11-30 05:15 UTC, RamyAlshurafa commented on server/modules/user/controllers/delete-user.js
>      next(error);
this doesn't match the same file in CoL

2022-11-30 05:15 UTC, RamyAlshurafa commented on server/modules/organisation/use-cases/delete-organisation.js
> +export default deleteOrganisation;
doesn't match the same file in CoL
Make sure to go through all the backend files again please

2022-11-30 08:37 UTC, fadeomar commented
hey @RamyAlshurafa can you work on the migration file point, please?

2022-12-01 05:31 UTC, RamyAlshurafa approved these changes

2022-12-01 05:31 UTC, merged