96 remove modal
yalla-coop/universal-credit-support pull request #97
Opened 2021-08-19 12:42 UTC by fadeomar

#### Issues this PR relates to
#96
=======

_NOTE: REMEMBER NOT TO REVIEW UNLESS ALL ACCEPTANCE CRITERIA HAS BEEN TICKED OFF_

---

#### Any info the reviewer needs to know to test 
e.g. Add env vars, run npm install

---

#### Any info the team needs to consider before merged into development
e.g. Will a database need to be rebuilt (and is this ok if existing data), add env vars

---

#### Quick Pull Request Checklist

Please make sure you ensure the following has been done before marking your PR as awaiting-review. 

- Branch is up to date with develop
- Project runs
- You can download and install locally, and run the project locally
- All existing and new features run without bugs
- Checked that features/design works across all agreed browsers + devices
- The new work has been checked with Axe accessibility checker and doesn't throw significant errors  
- Linter is used
- Code is consistent with agreed team style
- Naming of files is consistent with project 
- Tests all pass
- No console logs

2021-08-19 13:40 UTC, RamyAlshurafa requested changes
- [ ] avoid fix numbers in px
![image](https://user-images.githubusercontent.com/34629478/130078072-313c4214-c4d0-4300-b050-c16c64c01d48.png)

2021-08-19 13:40 UTC, RamyAlshurafa commented on client/src/components/Layout/Step/style.js
> +  padding: ${({ theme: { spacings: s } }) =>
wrong values, don't match figma

2021-08-19 13:40 UTC, RamyAlshurafa commented on client/src/pages/Step/index.js
> +    <>
```suggestion
```

2021-08-22 07:12 UTC, fadeomar commented on client/src/components/Layout/Step/style.js
> +  padding: ${({ theme: { spacings: s } }) =>
done

2021-08-22 07:13 UTC, fadeomar commented on client/src/pages/Step/index.js
> +    <>
done

2021-08-22 09:33 UTC, thejoefriel approved these changes

2021-08-22 09:33 UTC, merged